[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = [
  'echo "Installing API dependencies..."',
  'pnpm install --no-frozen-lockfile',
  'echo "Dependencies installed"'
]

[phases.build]
cmds = [
  'echo "Building API..."',
  'pnpm prisma generate',
  'pnpm build',
  'echo "API build complete"'
]

[start]
cmd = 'node dist/main.js'
