[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['pnpm install --no-frozen-lockfile']

[phases.build]
cmds = [
  'pnpm --filter api exec prisma generate',
  'pnpm --filter api build'
]

[phases.deploy]
cmds = [
  'cd api && pnpm prisma migrate deploy'
]

[start]
cmd = 'cd api && PORT=$PORT node dist/main.js'
