[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = [
  'echo "Installing API dependencies..."',
  'pnpm install --no-frozen-lockfile',
  'echo "Dependencies installed"'
]

[phases.build]
cmds = [
<<<<<<< HEAD
  'echo "Building API..."',
  'pnpm prisma generate',
  'pnpm build',
  'echo "API build complete"'
]

[start]
cmd = 'node dist/main.js'
=======
  'pnpm --filter api exec prisma generate',
  'pnpm --filter api build'
]

[phases.deploy]
cmds = [
  'cd api && pnpm prisma migrate deploy'
]

[start]
cmd = 'cd api && PORT=$PORT node dist/main.js'
>>>>>>> api-deployment
