[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['pnpm install --no-frozen-lockfile']

[phases.build]
cmds = [
  'echo "Building API..."',
  'pnpm --filter api exec prisma generate',
  'pnpm --filter api build',
  'echo "API build complete"'
]

[start]
cmd = 'cd api && node dist/main.js'
