[variables]
NIXPACKS_NIXPKGS = "nodejs_18 pnpm"

[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm build',
  'echo "Build completed, checking .next directory:"',
  'ls -la .next/',
  'echo "Checking for standalone directory:"',
  'ls -la .next/standalone/ 2>/dev/null || echo "No standalone directory found"'
]

[start]
cmd = 'pnpm start'