[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['cd .. && pnpm install --no-frozen-lockfile']

[phases.build]
cmds = ['cd .. && pnpm --filter app build']

[start]
cmd = 'cd .. && pnpm --filter app start'
