[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = [
  'echo "Installing frontend dependencies..."',
  'pnpm install --no-frozen-lockfile',
  'echo "Dependencies installed"'
]

[phases.build]
cmds = [
  'echo "Building frontend..."',
  'pnpm build',
  'echo "Frontend build complete"'
]

[start]
cmd = 'pnpm start'
