[variables]
NIXPACKS_NIXPKGS = "nodejs_18 pnpm"

[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm --filter launchkit-frontend build',
  'echo "Build completed, checking app/.next directory:"',
  'ls -la app/.next/',
  'echo "Checking for standalone directory:"',
  'ls -la app/.next/standalone/ 2>/dev/null || echo "No standalone directory found"'
]

[start]
cmd = 'cd app && pnpm start'