[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = [
  'cd api && pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'cd api && pnpm prisma generate',
  'cd api && pnpm run build'
]

[start]
cmd = 'cd api && PORT=$PORT node dist/main.js'
