[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'cd api && pnpm prisma generate --schema=./prisma/schema.prisma',
  'cd api && pnpm run build',
  'cp -r api/dist ./dist'
]

[phases.deploy]
cmds = [
  'pnpm prisma db push --schema=prisma/schema.prisma'
]

[start]
cmd = 'node dist/main.js'
