[build]
builder = "dockerfile"
dockerfilePath = "api/Dockerfile"

[deploy]
startCommand = "cd api && pnpm prisma db push && node dist/main.js"
healthcheckPath = "/v1/ping"
healthcheckTimeout = 60

[networking]
port = 8080
