[build]
builder = "dockerfile"
dockerfilePath = "api/Dockerfile"

[deploy]
startCommand = "pnpm prisma db push --schema=api/prisma/schema.prisma && node dist/main.js"
healthcheckPath = "/v1/ping"
healthcheckTimeout = 60

[networking]
port = 8080
